version: "3.5"

services:
  nginx:
    image: nginx:alpine
    working_dir: /application
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/application
    ports:
      - '${HTTP_PORT}:80'
    depends_on:
      - php-fpm
    tty: true

  php-fpm:
      build: docker/php
      working_dir: /application
      volumes:
          - ./:/application
      ports:
          - '9000'
      links:
          - postgres

  portainer:
    image: portainer/portainer
    command: --admin-password '123456'
    volumes:
      - ./docker/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000

  postgres:
    image: postgres:12.6
    restart: always
    environment:
      POSTGRES_USER: someuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - '${DB_PORT}:5432'

  phppgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
